### ISSUE TITLE
The graphic quality is lower than the ZkxRP ... I feeling ...

### ISSUE THREAD

**Issue by okzkx** [zlygithub-98/ZhuangDong_Shader#2]

**Comment by okzkx** [comment]
?

**Comment by okzkx** [comment]
南瓜大魔王 yyds

**Comment by DarkAbysser** [comment]
> 南瓜大魔王 yyds

?

**Comment by okzkx** [comment]
### ****

> 

?

**Comment by okzkx** [comment]
> > 南瓜大魔王 yyds
> 
> ?

?

**Comment by DarkAbysser** [comment]
> ### ****
> > 
> 
> ?

叫我干哈

**Comment by okzkx** [comment]
不会用 GitHub

**Comment by DarkAbysser** [comment]
> 

你都能呼唤我了  不会用个der

**Comment by okzkx** [comment]
> > 
> 
> 你都能呼唤我了 不会用个der

可能是引用自动的

**Comment by DarkAbysser** [comment]
> > > 
> > 
> > 
> > 你都能呼唤我了 不会用个der
> 
> 可能是引用自动的


![C~RRL9%%N}73AB}ZLY_ 71T](https://user-images.githubusercontent.com/59312213/157620919-4254b14b-0f7d-47fe-93a4-669be85f1314.jpg)

**Comment by okzkx** [comment]
> 
![2TS$(SJDD_@YN31INJ6{JK9](https://user-images.githubusercontent.com/31460809/157621306-b7383929-5ab4-4ec7-b81d-3bf95fa8eadb.jpg)
还能发图啊
